name: Tag commit

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      commit_sha:
        required: true
        type: string
      ref:
        required: false
        type: string
        default: 'build'


jobs:

  tag_commit:    
    name: Tag commit
    
    runs-on: ubuntu-latest    
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: '0'

      - name: Print commit sha
        run: echo ${{ inputs.commit_sha }}

      - name: Delete local tag        
        run : git tag -d  ${{ inputs.tag_name }} || true

      - name: Delete remote tag
        run : git push --delete origin  ${{ inputs.tag_name }} || true                 

      - name: Tag commit
        run : |
          git tag  ${{ inputs.tag_name }} ${{ inputs.commit_sha }}
          git push origin  ${{ inputs.tag_name }}          
