name: Tag commit

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      commit_sha:
        required: true
        type: string      


jobs:

  tag_commit:    

    runs-on: ubuntu-latest    
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: 'build'
          fetch-depth: '0'

      - name: Print commit sha
        run: echo ${{ inputs.commit_sha }}

      - name: Tag commit
        run : |
          git tag  ${{ inputs.tag_name }} ${{ inputs.commit_sha }}
          git push origin  ${{ inputs.tag_name }}          