name: unit_tests_prod
on:
  workflow_call
jobs:
  unit_tests_prod:
    name: unit tests for production
    runs-on: ubuntu-latest
    steps:
      - name: checks
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10 #install the python needed

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: fetch / install requirements # run the run.py to get the latest data
        run: |
          git fetch --prune
          git config pull.rebase true
          git pull origin ${{ steps.extract_branch.outputs.branch }}
          pip install -r requirements_prod.txt
          pip install pytest

      - name: Dvc pull
        run: |
          pip install boto3 dvc['s3']
          dvc pull
          if dvc repro --dry | grep 'Running stage'
          then
              echo "dvc is not up to date !"
              exit 1
          fi

      - name: unit test
        run: |
          echo "pytest"
          pytest -v unit_tests/test_prod.py
